# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: "175810268976"
  secret_key: 9dc7287adbe8c57630c38e6b6e6b8c31
  canvas_page_name: wt-games-test
  callback_url: http://www.hadok.com:3000
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: hasan
    public_host: restaurant.welltreat.us
    ssh_port: 2212
    public_port: 8333
    local_port: 80
    server_alive_interval: 0

test:
  api_key: 15b8a8040af0fe31fc46da4867ab6488
  secret_key: 492ddee03156bcecd8f57c6f44de3ca9
  canvas_page_name:
  callback_url: http://hadok.com/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:

production:
  api_key: 188534968205
  secret_key: af4c511f8d8d41aa940a3226c95eb236
  canvas_page_name: well_treat_us
  callback_url: http://www.welltreat.us/games/
  set_asset_host_to_callback_url: false
  tunnel:

staging:
  api_key: be437507fb7096f8faf2d9d9cda1607f
  secret_key: af4c511f8d8d41aa940a3226c95eb236
  canvas_page_name: well_treat_us
  callback_url: http://www.welltreat.us/games/
  set_asset_host_to_callback_url: false
  tunnel:

